"""empty message

Revision ID: 3c5d44f28bf2
Revises: a7ea4520e023
Create Date: 2023-01-18 20:52:59.136663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5d44f28bf2'
down_revision = 'a7ea4520e023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.drop_column('link_group')

    with op.batch_alter_table('boosty', schema=None) as batch_op:
        batch_op.drop_column('link_group')

    with op.batch_alter_table('buymeacoffe', schema=None) as batch_op:
        batch_op.drop_column('link_group')

    with op.batch_alter_table('cloudtips', schema=None) as batch_op:
        batch_op.drop_column('link_group')

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('link_group')

    with op.batch_alter_table('facebook', schema=None) as batch_op:
        batch_op.drop_column('link_group')

    with op.batch_alter_table('instagram', schema=None) as batch_op:
        batch_op.drop_column('link_group')

    with op.batch_alter_table('twitter', schema=None) as batch_op:
        batch_op.drop_column('link_group')

    with op.batch_alter_table('vkontakte', schema=None) as batch_op:
        batch_op.drop_column('link_group')

    with op.batch_alter_table('youtube', schema=None) as batch_op:
        batch_op.drop_column('link_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_group', sa.VARCHAR(length=2), nullable=True))

    with op.batch_alter_table('vkontakte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_group', sa.VARCHAR(length=2), nullable=True))

    with op.batch_alter_table('twitter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_group', sa.VARCHAR(length=2), nullable=True))

    with op.batch_alter_table('instagram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_group', sa.VARCHAR(length=2), nullable=True))

    with op.batch_alter_table('facebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_group', sa.VARCHAR(length=2), nullable=True))

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_group', sa.VARCHAR(length=2), nullable=True))

    with op.batch_alter_table('cloudtips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_group', sa.VARCHAR(length=2), nullable=True))

    with op.batch_alter_table('buymeacoffe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_group', sa.VARCHAR(length=2), nullable=True))

    with op.batch_alter_table('boosty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_group', sa.VARCHAR(length=2), nullable=True))

    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_group', sa.VARCHAR(length=2), nullable=True))

    # ### end Alembic commands ###
