"""empty message

Revision ID: 691cb377d9ae
Revises: 4dc52674bc12
Create Date: 2023-02-10 01:19:01.641356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691cb377d9ae'
down_revision = '4dc52674bc12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coun2', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_column('coun2')

    # ### end Alembic commands ###
