"""empty message

Revision ID: 7f417478f769
Revises: add21b9bad68
Create Date: 2023-02-10 00:38:48.644130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f417478f769'
down_revision = 'add21b9bad68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_UUID', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['payment_UUID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('payment_UUID')

    # ### end Alembic commands ###
