"""empty message

Revision ID: f901586797da
Revises: c7391931cdef
Create Date: 2023-02-10 00:04:28.105776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f901586797da'
down_revision = 'c7391931cdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('API_key')
        batch_op.drop_column('API_counter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('API_counter', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('API_key', mysql.VARCHAR(length=12), nullable=True))

    # ### end Alembic commands ###
