networks_data = {
       'about': {'url': '',
                 'is_free': True,
                 'group': 'information',
                 'icon_name': 'ti-user',
                 'repr_name': 'About',
                 'share_url': False,
                 },

       'email': {'url': 'mailto:',
                 'is_free': True,
                 'group': 'emails',
                 'icon_name': 'ti-at',
                 'repr_name': 'Email',
                 'share_url': False,
                 },

       'facebook': {'url': 'https://facebook.com/',
                    'is_free': True,
                    'group': 'social_media',
                    'icon_name': 'ti-brand-facebook',
                    'repr_name': 'Facebook',
                    'share_url': 'https://www.facebook.com/sharer.php?u=',
                    },

       'twitter': {'url': 'https://twitter.com/',
                   'is_free': True,
                   'group': 'social_media',
                   'icon_name': 'ti-brand-twitter',
                   'repr_name': 'Twitter',
                   'share_url': 'https://twitter.com/intent/tweet?text=allme&hashtags=allme,&url=',
                   },

       'vk': {'url': 'https://vk.com/',
              'is_free': False,
              'group': 'social_media',
              'icon_name': 'ti-brand-vk',
              'repr_name': 'VKontakte',
              'share_url': False,
              },

       'instagram': {'url': 'https://instagram.com/',
                     'is_free': True,
                     'group': 'social_media',
                     'icon_name': 'ti-brand-instagram',
                     'repr_name': 'Instagram',
                     'share_url': False,
                     },

       'youtube': {'url': 'https://youtube.com/@',
                   'is_free': True,
                   'group': 'social_media',
                   'icon_name': 'ti-brand-youtube',
                   'repr_name': 'YouTube',
                   'share_url': False,
                   },

       'buymeacoffe': {'url': 'https://www.buymeacoffee.com/',
                       'is_free': True,
                       'group': 'donate_world',
                       'icon_name': 'ti-currency-dollar',
                       'repr_name': 'Buy me a coffee',
                       'share_url': False,
                       },

       'cloudtips': {'url': 'https://pay.cloudtips.ru/p/',
                     'is_free': True,
                     'group': 'donate_russia',
                     'icon_name': 'ti-currency-rubel',
                     'repr_name': 'CloudTips',
                     'share_url': False,
                     },

       'boosty': {'url': 'https://boosty.to/',
                  'is_free': False,
                  'group': 'donate_russia',
                  'icon_name': 'ti-currency-rubel',
                  'repr_name': 'Boosty',
                  'share_url': False,
                  },

       'telegram': {'url': 'https://t.me/',
                    'is_free': True,
                    'group': 'messengers',
                    'icon_name': 'ti-brand-telegram',
                    'repr_name': 'Telegram',
                    'share_url': 'https://t.me/share/url?text=allme&url=',
                    },

       'github': {'url': 'https://github.com/',
                  'is_free': True,
                  'group': 'development',
                  'icon_name': 'ti-brand-github',
                  'repr_name': 'GitHub',
                  'share_url': False,
                  },

       'playmarket': {'url': 'https://play.google.com/store/apps/developer?id=',
                      'is_free': True,
                      'group': 'development',
                      'icon_name': 'ti-brand-google-play',
                      'repr_name': 'Google Play',
                      'share_url': False,
                      },

       'linkedin': {'url': 'https://www.linkedin.com/in/',
                    'is_free': True,
                    'group': 'social_media',
                    'icon_name': 'ti-brand-linkedin',
                    'repr_name': 'LinkedIn',
                    'share_url': 'https://www.linkedin.com/sharing/share-offsite/?url=',
                    },

       'flickr': {'url': 'https://www.flickr.com/photos/',
                  'is_free': True,
                  'group': 'collections',
                  'icon_name': 'ti-brand-flickr',
                  'repr_name': 'Flickr',
                  'share_url': False,
                  },

       'gitlab': {'url': 'https://gitlab.com/',
                  'is_free': True,
                  'group': 'development',
                  'icon_name': 'ti-brand-gitlab',
                  'repr_name': 'GitLab',
                  'share_url': False,
                  },

       'stackoverflow': {'url': 'https://stackoverflow.com/users/',
                         'is_free': True,
                         'group': 'development',
                         'icon_name': 'ti-brand-stackoverflow',
                         'repr_name': 'stack overflow',
                         'share_url': False,
                         },

              }
